/**
 * Demo stand-in for the SDK's pkce.js, wired by the import map in
 * index.html. connectRedirect() normally creates the grant request at the
 * vault and navigates this tab to the grant screen. Here it records the
 * request the SDK would send and stays on the page. Nothing is fetched.
 */
let last = null;

export async function connectRedirect(opts) {
  last = {
    url: (opts.baseUrl ?? "https://api.useoutlet.dev/v0") + "/grants",
    body: {
      app_id: opts.appId,
      providers: opts.providers,
      requested_cap_usd: opts.requestedCapUsd,
      redirect_uri: opts.redirectUri,
      code_challenge: "<S256 challenge, generated by the SDK>",
      code_challenge_method: "S256",
      state: "<random, kept in sessionStorage>",
    },
  };
  document.dispatchEvent(new CustomEvent("outlet-demo-redirect"));
  return { grantRequestId: "gr_demo", grantUrl: "", verifier: "", state: "" };
}

export function lastRequest() {
  return last;
}
